# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{rubyapp}
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kristian Mandrup"]
  s.date = %q{2010-06-06}
  s.default_executable = %q{rubyapp}
  s.description = %q{Create a fully configured ruby project with a set of common frameworks to choose from}
  s.email = %q{kmandrup@gmail.com}
  s.executables = ["rubyapp"]
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    ".gitignore",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "bin/rubyapp",
     "lib/application.thor",
     "lib/ruby_app.rb",
     "templates/Gemfile",
     "templates/MITLICENSE",
     "templates/_signatures/APP.RUBY.signature",
     "templates/autotest.options",
     "templates/autotest/discover.rb",
     "templates/bin/binary",
     "templates/bin/binary.bat",
     "templates/config/cucumber.yml",
     "templates/cucumber.yml",
     "templates/features/app_name.feature.erb",
     "templates/features/step_definitions/app_name_steps.erb",
     "templates/features/support/env.rb.erb",
     "templates/gitignore",
     "templates/lib/app_entrypoint.erb",
     "templates/lib/app_name.rb.erb",
     "templates/shoulda/test_app_name.rb.erb",
     "templates/spec/app_name/sample_spec.rb.erb",
     "templates/spec/rspec.options",
     "templates/spec/spec_helper.rb.erb",
     "templates/test/test_app_name.rb.erb"
  ]
  s.homepage = %q{http://github.com/kristianmandrup/rubyapp}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Create a fully configured ruby project}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

