source :gemcutter

<%= "gem 'require-me',  '>=0.7.6'"          if options[:require_me] %>    

group :test do                                
  <%= "gem 'rspec',     '>=2.0.0.beta.9'"   if options[:rspec] %>  
  <%= "gem 'cucumber',  '>=0.7.3'"          if options[:cucumber] %> 
  <%= "gem '#{options[:mock_lib]}'" %>
end