source :gemcutter

<%= "gem 'require-me',  '>=0.7.6'"          if project_options[:require_me] %>    

group :test do                                
  <%= "gem 'rspec',     '>=2.0.0.beta.9'"   if project_options[:rspec] %>  
  <%= "gem 'cucumber',  '>=0.7.3'"          if project_options[:cucumber] %> 
  <%= "gem '#{project_options[:mock_lib]}'" %>
end